"""
Django settings for sasbanking project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import boto3
import json
from django.core.exceptions import ImproperlyConfigured
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h(@qq+v=$i&t%r)rh$%vr-c%r-i)z^-vn5zz0j64h*foe(sgim'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ALLOWED_HOSTS = ['*']

#LOGIN_URL = '/login/'
#LOGIN_REDIRECT_URL = '/'
#LOGOUT_REDIRECT_URL = '/login/'
#LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'widget_tweaks',
    'fraud',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sasbanking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sasbanking.wsgi.application'

#Secret for email
def email_get_secret():
    try:
        client = boto3.client("secretsmanager", region_name="eu-west-2")
        response = client.get_secret_value(
            SecretId="arn:aws:secretsmanager:eu-west-2:320368024742:secret:email_credentials-wHogpZ"
        )
        return json.loads(response["SecretString"])
    except Exception as e:
        raise ImproperlyConfigured(f"Secrets Manager error: {e}")

email_secret = email_get_secret()

# Email backend
EMAIL_BACKEND = email_secret["EMAIL_BACKEND"]
EMAIL_HOST = email_secret["EMAIL_HOST"]
EMAIL_PORT = email_secret["EMAIL_PORT"]
EMAIL_USE_TLS = email_secret["EMAIL_USE_TLS"]
EMAIL_HOST_USER = email_secret["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = email_secret["EMAIL_HOST_PASSWORD"]
DEFAULT_FROM_EMAIL = email_secret["DEFAULT_FROM_EMAIL"]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



def get_secret():
    try:
        client = boto3.client("secretsmanager", region_name="eu-west-2")
        response = client.get_secret_value(
            SecretId="arn:aws:secretsmanager:eu-west-2:320368024742:secret:rds!cluster-6bc850ab-c477-4c73-aeb4-7ea495033a48-OROum2"
        )
        return json.loads(response["SecretString"])
    except Exception as e:
        raise ImproperlyConfigured(f"Secrets Manager error: {e}")

secret = get_secret()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "postgres",
        'USER': secret['username'],
        'PASSWORD': secret['password'],
        'HOST': "sasbanking.cluster-cn2a02ecom74.eu-west-2.rds.amazonaws.com",
        'PORT': "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


